### ISSUE TITLE
Copy QTWidgets pyi file and determine relevant methods

### ISSUE THREAD

**Issue by DerkNiessink** [NatuurkundePracticumAmsterdam/PySide6-compact-documentation#1]
Additional info: comment the less important methods.

**Comment by Thijs-de-Z** [comment]
Relevent QtWidgets are:
QHBoxLayout
QVBoxLayout
QFormLayout
QLabel
QGroupBox
QComboBox
QPushButton
QSpinbox
QDoubleSpinbox
QCheckBox
QTextEdit

I also included QMainWindow in the file, as this is used as inheritance. However, it is often only used for inheritance, thus for beginners it is not necessary to understand this class.

**Comment by Thijs-de-Z** [comment]
Relevant methods per class. Everything with an * is not relevant for beginners and will be implemented if time allows.

- [ ] QHBoxLayout:


- [ ] QVBoxLayout:


- [ ] QFormLayout:
  - [ ] addItem
  - [ ] addRow

- [ ] QLabel:
  - [ ] setText

- [ ] QGroupBox:


- [ ] QComboBox:
  - [ ] addItem
  - [ ] addItems*
  - [ ] clear*
  - [ ] currentText
  - [ ] currentIndex
  - [ ] removeItem*
  - [ ] setCurrentIndex*
  - [ ] setCurrentText*
  - [ ] setText (inherited from QWidget)

- [ ] QPushButton:
  - [ ] setText (inherited from QAbstractButton)

- [ ] QSpinbox:
  - [ ] setMinimum
  - [ ] setMaximum
  - [ ] setValue
  - [ ] value

- [ ] QDoubleSpinbox:
  - [ ] setMaximum
  - [ ] setMinimum
  - [ ] setRange*
  - [ ] setValue
  - [ ] value

- [ ] QCheckBox*:
  - [ ] IsChecked (inherited from QAbstractButton)

- [ ] QTextEdit*:
