### ISSUE TITLE
Structure of examples in the API reference

### ISSUE THREAD

**Issue by DerkNiessink** [NatuurkundePracticumAmsterdam/PySide6-compact-documentation#39]
Some examples in the API reference show a widget being constructed, for example:
```py
widget = QtWidgets.QWidget()
```
When running this code, it gives rise to the error:
```
> QWidget: Must construct a QApplication before a QWidget
```
We have to consider if we will we take this into account in the examples, i.e. constructing a `QApplication` before constructing a `QWidget` in every example. I am leaning towards not doing this. It is anyway not possible to directly copy the code in vscode and running it, because of missing import statements.

**Comment by AnneliesVlaar** [comment]
To have examples that can run and give output we need to provide a lot of extra code. I agree not to provide this.

**Comment by AnneliesVlaar** [comment]
It might be usefull to provide the import statements. I was checking the example code of QComboBox using the example code of the tutorial.
```
combo = QComboBox()
````
doesn't work, you need to do ```combo = QtWidgets.QComboBox()``` or import ```from PySide6.QtWidgets import QComboBox```.

In the numpy examples the first line is always importing numpy. We can add a line to construct a QApplication and create a working example (however it is not a full GUI). For example:
```
import PySide6
from PySide6.QtWidgets import QComboBox

app = PySide6.QtWidgets.QApplication()

combo = QComboBox()
combo.addItem("Option 1")
combo.addItems("[Option 2, Option 3]")
print(combo.currentText())
```

**Comment by AnneliesVlaar** [comment]
@DerkNiessink there is a small error in the above example with option 2 and 3, I will commit a correction

**Comment by davidfokkema** [comment]
That's a lot of extra code indeed. I would be totally fine with this example:
```python
combo = QtWidgets.QComboBox()
combo.addItem("Option 1")
combo.addItems(["Option 2", "Option 3"])
print(combo.currentText())
```
i.e. _not_ adding the imports and the `QApplication`. By including `QtWidgets` I think it is clear enough where the widget comes from. The reason for me to only use a short piece of code is that the full code Annelies demonstrates still is not entirely complete. While it works, it doesn't display anything. The widget is not added to a main window for example. So a user still can't run that code. It should be even longer:
```python
from PySide6 import QtWidgets

app = QtWidgets.QApplication()
window = QtWidgets.QMainWindow()

combo = QtWidgets.QComboBox()
window.setCentralWidget(combo)
combo.addItem("Option 1")
combo.addItems(["Option 2", "Option 3"])

window.show()
app.exec()

print(combo.currentText())
```
Here, the user can interact with the combobox, select an option and on exit the currently selected option will be printed.

In my opinion, this is overkill. When the user is browsing widgets, she'll already have an application constructed. Just show the code that is necessary to create and interact with the widget, I think.

**Comment by DerkNiessink** [comment]
@davidfokkema I agree. I will stick with this structure:
```py
combo = QtWidgets.QComboBox()
combo.addItem("Option 1")
combo.addItems(["Option 2", "Option 3"])
print(combo.currentText())
```

**Comment by DerkNiessink** [comment]
I have another question about the structure of the examples, @AnneliesVlaar @davidfokkema, specifically about the print statements. What is in your opinion better:

### 1. Showing intermediate prints
```py
spin_box = QtWidgets.QSpinBox()
spin_box.setMaximum(100)
spin_box.setValue(50)
print(spin_box.value())
```
`50`
```py
spin_box.setValue(200)
print(spin_box.value())
```
`100`

### 2. Showing prints after the full code block

```py
spin_box = QtWidgets.QSpinBox()
spin_box.setMaximum(100)
spin_box.setValue(50)
print(spin_box.value())
spin_box.setValue(200)
print(spin_box.value())
```
`50`
`100`

**Comment by davidfokkema** [comment]
Or maybe:
```python
spin_box = QtWidgets.QSpinBox()
spin_box.setMaximum(100)
spin_box.setValue(50)
value = spin_box.value()
# value = 50

spin_box.setValue(200)
value = spin_box.value()
# value = 100
# (because of the maximum value chosen earlier)
```

**Comment by AnneliesVlaar** [comment]
> Or maybe:
> 
> ```python
> spin_box = QtWidgets.QSpinBox()
> spin_box.setMaximum(100)
> spin_box.setValue(50)
> value = spin_box.value()
> # value = 50
> 
> spin_box.setValue(200)
> value = spin_box.value()
> # value = 100
> # (because of the maximum value chosen earlier)
> ```

I like the extra comment on why it is 100 instead of 200. But we don't want to put the output as a comment in the code block, it is confusing for beginners. 
If you split the code blocks the second block is not runable, but it is much better for reading and understanding, I would go for showing intermediate print statements.

**Comment by DerkNiessink** [comment]
@AnneliesVlaar I agree. As this is a documentation for beginner, I will go with the intermediate print statements.

**Comment by DerkNiessink** [comment]
Added all improvements discussed in this issue in #47.
