### ISSUE TITLE
Add installation guide

### ISSUE THREAD

**Issue by DerkNiessink** [NatuurkundePracticumAmsterdam/PySide6-compact-documentation#5]

**Comment by Thijs-de-Z** [comment]
I added a first concept of the installation guide.

**Comment by DerkNiessink** [comment]
Nice!!!

**Comment by AnneliesVlaar** [comment]
> I added a first concept of the installation guide.

De installation guide is nu heel specifiek geschreven voor onze studenten met conda en poetry. poetry gebruikt pip dus blijkbaar kan je het ook met pip installeren. Pyside6 laat het zien met python environments en pip (https://wiki.qt.io/Qt_for_Python). Je kunt de numpy installation guide gebruiken voor inspiratie om het wat algemener te maken https://numpy.org/install/.

**Comment by DerkNiessink** [comment]
Ik ga hier nu aan verder werken. @AnneliesVlaar, mee eens, ik ga de Numpy installation guide gebruiken als inspiratie.
