### ISSUE TITLE
Documentation of signal classes

### ISSUE THREAD

**Issue by Thijs-de-Z** [NatuurkundePracticumAmsterdam/PySide6-compact-documentation#6]
When using signals, for example, when a button is clicked or a spin box is changed, a method of a class variable is used. This requires different syntax than normal class methods. The question/problem is how to explain this.

**Comment by DerkNiessink** [comment]
This issue was fixed in #28. Each `QtWidgets` class has now a list of Signals in the API Reference. As an example `QComboBox`:

![Screenshot 2024-09-18 121004](https://github.com/user-attachments/assets/9a1451f0-7a19-40e2-ac9b-f634be86799b)
